name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Execute every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        id: generate-snake
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Create output directory
        run: mkdir -p dist

      - name: Move snake.svg to dist directory
        run: mv snake.svg dist/

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
